version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: todo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abcd1234.
    ports:
      - "5432:5432"
